### PR TITLE
Add install instructions to README.

### PR DESCRIPTION
**Pull request by mbucc**

### CODE REVIEW

**Comment by paul-j-lucas** [comment]
Installation instructions should be added to the INSTALL file, not the README.

**Comment by mbucc** [comment]
Install file references README.

**Comment by paul-j-lucas** [comment]
Point taken. OK, I've submitted my own patch. that copies the text (with better formatting than your patch) from the previously open issue on this same topic.

**Comment by mbucc** [comment]
Cool, thanks.  That previous issue is actually how I figured out how to build :).

**Pull request closed without merging**
